source /usr/local/etc/ocp4.config

export U=$RHT_OCP4_DEV_USER
export P=$RHT_OCP4_DEV_PASSWORD
export D=$RHT_OCP4_WILDCARD_DOMAIN
export M=$RHT_OCP4_MASTER_API

oc login -u $RHT_OCP4_DEV_USER -p $RHT_OCP4_DEV_PASSWORD $RHT_OCP4_MASTER_API
