FROM ubi8/ubi:8.5

MAINTAINER Red Hat Training <nexweb1@gmail.com>

Label Component="wildy java" \
      Name="wildy disp" \
      Version="1.0.1" \
      Release="1.0"  \
      Description="wildfly desc"

Label io.k8s.description="K8S desc" \
      io.k8s.display-name="k8s disp" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="wildfly,java"

ENV APP_ROOT=/opt/app-root \
    PORT=8080 \
    JAVA_OPTIONS="-Xmx512m"

RUN yum install -y --nodocs --disableplugin=subscription-manager java-1.8.0-openjdk-headless && \
    yum clean all --disableplugin=subscription-manager -y && \
    groupadd -r wildfly -f -g 1001 && \
    useradd wildfly -u 1001 -g wildfly -m -d /home/wildfly -s /sbin/nologin && \
    mkdir -p ${APP_ROOT}/bin

ADD https://github.com/RedHatTraining/DO288-apps/releases/download/OCP-4.1-1/hello-java.jar ${APP_ROOT}/bin

COPY ./app-run.sh /opt/app-root/bin/

RUN chown -R wildfly:wildfly ${APP_ROOT}/ && \
    chgrp -R 0 ${APP_ROOT}/ && \
    chmod -R g=u ${APP_ROOT}/ 

EXPOSE ${PORT}

USER wildfly

CMD /opt/app-root/bin/app-run.sh
