version: '3.8'

networks:
  database:

volumes:
  data:

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    networks:
     - database
    ports:
     - 3306:3306
    volumes:
     - ./data:/var/lib/mysql
     - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=passw0rd!
     - MYSQL_USER=user00
     - MYSQL_PASSWORD=admin1234
     - MYSQL_DATABASE=demo
     - TZ=Asia/Seoul

