version: "3"

networks:
  consul-net:

services:
  consul:
    container_name: consul
    image: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    networks:
      - consul-net
