apiVersion: v1
kind: Pod
metadata:
  labels:
    test: health-check
  name: my-probe
spec:
  containers:
  - name: my-container 
    args:
    image: k8s.gcr.io/goproxy:0.1 
    livenessProbe: 
      tcpSocket:  
        port: 8080 
      initialDelaySeconds: 15 
      periodSeconds: 20 
      timeoutSeconds: 10 
    readinessProbe: 
      httpGet: 
        host: my-host 
        scheme: HTTPS 
        path: /healthz
        port: 8080 
    startupProbe: 
      exec: 
        command: 
        - cat
        - /tmp/healthy
      failureThreshold: 30 
      periodSeconds: 20 
      timeoutSeconds: 10 
