apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: probes
  name: probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes
  template:
    metadata:
      labels: 
        app: probes
    spec:
      containers:
      - name: probes
        image: k8s.gcr.io/goproxy:0.1 
        livenessProbe: 
          tcpSocket:  
            port: 8080 
          initialDelaySeconds: 15 
          periodSeconds: 20 
          timeoutSeconds: 10 
        readinessProbe: 
          httpGet: 
            host: my-host 
            scheme: HTTPS 
            path: /healthz
            port: 8080 
        startupProbe: 
          exec: 
            command: 
            - cat
            - /tmp/healthy
          failureThreshold: 30 
          periodSeconds: 20 
          timeoutSeconds: 10 
