version: '3'

services:
  postgres:
    image: postgres:10
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgressql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/1-ddl.sql"
    environment:
      - POSTGRES_PASSWORD=passw0rd
    networks:
      - academy-net

networks:
  academy-net:
