apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  # storageClassName: ibmc-file-bronze
  storageClassName: nfs-standard
  resources:
    requests:
      storage: 1Gi
