# Use the httpd-parent image as base
FROM httpd-parent

ENV APP_DIRS /etc/httpd/logs/ /run/httpd/
ENV PORT=8080

RUN echo "Hello World using onbuild..." && \
    sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
    sed -i "s/container!/container! as rootless/g" ${DOCROOT}/index.html && \
    chown -R 1001:0 $APP_DIRS && \
    chgrp -R 0 $APP_DIRS && \
    chmod -R g=u $APP_DIRS 

EXPOSE ${PORT}

USER 1001


