# Use the httpd-parent image as base
FROM registry.access.redhat.com/ubi8/ubi:8.0

MAINTAINER Red Hat Training <nexweb1@gmail.com>

ENV DOCROOT=/var/www/html/

RUN yum install -y --nodocs --disableplugin=subscription-manager httpd && \
    yum clean all --disableplugin=subscription-manager -y && \
    sed -i 's/Listen 80/Listen 8080/g' /etc/httpd/conf/httpd.conf && \
    echo "Hello from the httpd-parent container!" > ${DOCROOT}/index.html && \
    chown -R 1001:0 /etc/httpd/logs/ /run/httpd/ && \
    chgrp -R 0 /etc/httpd/logs/ /run/httpd/ && \
    chmod  g=u /etc/httpd/logs/ /run/httpd/

ONBUILD COPY src/ ${DOCROOT}

EXPOSE 8080

USER 1001

CMD /usr/sbin/httpd -DFOREGROUND
